// <auto-generated />
using System;
using AvaliacaoCNPJ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AvaliacaoCNPJ.Migrations
{
    [DbContext(typeof(CnpjWebMvcContext))]
    [Migration("20200326141255_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AvaliacaoCNPJ.Models.ApiObjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abertura");

                    b.Property<string>("Bairro");

                    b.Property<int?>("BillingId");

                    b.Property<string>("Capital_social");

                    b.Property<string>("Cep");

                    b.Property<string>("Cnpj");

                    b.Property<string>("Complemnto");

                    b.Property<string>("Data_situacao");

                    b.Property<string>("Data_situacao_especial");

                    b.Property<string>("Efr");

                    b.Property<string>("Email");

                    b.Property<string>("Fantasia");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Message");

                    b.Property<string>("Motivo_situacao");

                    b.Property<string>("Municipio");

                    b.Property<string>("Natureza_juridica");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("Situacao");

                    b.Property<string>("Situacao_especial");

                    b.Property<string>("Status");

                    b.Property<string>("Telefone");

                    b.Property<string>("Tipo");

                    b.Property<string>("Uf");

                    b.HasKey("Id");

                    b.HasIndex("BillingId");

                    b.ToTable("ApiObjeto");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Atividade_principal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApiObjetoId");

                    b.Property<string>("Code");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ApiObjetoId");

                    b.ToTable("Atividade_principal");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Atividades_secundarias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApiObjetoId");

                    b.Property<string>("Code");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ApiObjetoId");

                    b.ToTable("Atividades_secundarias");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Free");

                    b.Property<bool>("database");

                    b.HasKey("Id");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Qsa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApiObjetoId");

                    b.Property<string>("Nome");

                    b.Property<string>("Nome_rep_legal");

                    b.Property<string>("Qual");

                    b.Property<string>("Qual_rep_legal");

                    b.Property<string>("pais_origem");

                    b.HasKey("Id");

                    b.HasIndex("ApiObjetoId");

                    b.ToTable("Qsa");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.ApiObjeto", b =>
                {
                    b.HasOne("AvaliacaoCNPJ.Models.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingId");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Atividade_principal", b =>
                {
                    b.HasOne("AvaliacaoCNPJ.Models.ApiObjeto", "ApiObjeto")
                        .WithMany("Atividade_principal")
                        .HasForeignKey("ApiObjetoId");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Atividades_secundarias", b =>
                {
                    b.HasOne("AvaliacaoCNPJ.Models.ApiObjeto", "ApiObjeto")
                        .WithMany("atividades_secundarias")
                        .HasForeignKey("ApiObjetoId");
                });

            modelBuilder.Entity("AvaliacaoCNPJ.Models.Qsa", b =>
                {
                    b.HasOne("AvaliacaoCNPJ.Models.ApiObjeto", "ApiObjeto")
                        .WithMany("Qsa")
                        .HasForeignKey("ApiObjetoId");
                });
#pragma warning restore 612, 618
        }
    }
}
